version: 2.1

scala_212: &scala_212
  SCALA_VERSION: 2.12.12

scala_213: &scala_213
  SCALA_VERSION: 2.13.3

jdk_8: &jdk_8
  JDK_VERSION: 8

jdk_11: &jdk_11
  JDK_VERSION: 11

machine_resource: &machine_resource
  resource_class: large

machine_ubuntu: &machine_ubuntu
  machine:
    image: ubuntu-1604:201903-01

install_jdk: &install_jdk
  - run:
      name: Install JDK
      command: |
        while $(ps aux | grep -i ' apt ' | grep -v grep > /dev/null); do sleep 1; done # Wait for apt to be ready

        sudo rm /etc/apt/sources.list.d/*
        sudo tee /etc/apt/sources.list > /dev/null \<< 'EOF'
        deb http://mirror.math.princeton.edu/pub/ubuntu/ xenial main universe
        deb http://mirror.math.princeton.edu/pub/ubuntu/ xenial-updates main universe
        deb http://mirror.math.princeton.edu/pub/ubuntu/ xenial-backports main universe
        deb http://mirror.math.princeton.edu/pub/ubuntu/ xenial-security main restricted universe
        EOF

        if [ $JDK_VERSION == 11 ]; then
          wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
          sudo add-apt-repository https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ -y
        fi
        sudo apt update
        if [ $JDK_VERSION == 11 ]; then
          sudo apt install -y adoptopenjdk-11-hotspot
        elif [ $JDK_VERSION == 8 ]; then
          sudo apt install -y openjdk-8-jdk
        fi
        java -version

load_cache: &load_cache
  - restore_cache:
      key: sbt-cache-interop-cats-2

clean_cache: &clean_cache
  - run:
      name: Clean unwanted files from cache
      command: |
        rm -fv $HOME/.ivy2/.sbt.ivy.lock
        find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
        find $HOME/.sbt        -name "*.lock"               -print -delete

save_cache: &save_cache
  - save_cache:
      key: sbt-cache-interop-cats-2
      paths:
          - "~/.ivy2/cache"
          - "~/.sbt"
          - "~/.m2"
          - "~/.cache"

filter_tags: &filter_tags
  tags:
    only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

lint: &lint
  steps:
    - checkout
    - <<: *load_cache
    - run:
        name: Lint code
        command: ./sbt ++${SCALA_VERSION}! check
    - <<: *clean_cache
    - <<: *save_cache

testJVM: &testJVM
  steps:
    - checkout
    - <<: *load_cache
    - <<: *install_jdk
    - run:
        name: Run tests
        command: ./sbt ++${SCALA_VERSION}! testJVM
    - <<: *clean_cache
    - <<: *save_cache
    - store_test_results:
        path: core-tests/jvm/target/test-reports

testJS: &testJS
  steps:
    - checkout
    - <<: *load_cache
    - <<: *install_jdk
    - run:
        name: Run tests
        command: ./sbt ++${SCALA_VERSION}! testJS
    - <<: *clean_cache
    - <<: *save_cache
    - store_test_results:
        path: core-tests/js/target/test-reports

release: &release
  steps:
      - checkout
      - run:
          name: Fetch git tags
          command: git fetch --tags
      - <<: *load_cache
      - run:
          name: Write sonatype credentials
          command: echo "credentials += Credentials(\"Sonatype Nexus Repository Manager\", \"oss.sonatype.org\", \"${SONATYPE_USER}\", \"${SONATYPE_PASSWORD}\")" > ~/.sbt/1.0/sonatype.sbt
      - run:
          name: Write PGP public key
          command: echo -n "${PGP_PUBLIC}" | base64 -di > /tmp/public.asc
      - run:
          name: Write PGP secret key
          command: echo -n "${PGP_SECRET}" | base64 -di > /tmp/secret.asc
      - run:
          name: Release artifacts
          command: |
            mkdir -p $HOME/bin
            sudo apt-get update && sudo apt-get -y install gnupg2
            echo pinentry-mode loopback >> ~/.gnupg/gpg.conf
            echo allow-loopback-pinentry >> ~/.gnupg/gpg-agent.conf
            chmod 600 ~/.gnupg/*
            ln -s /usr/bin/gpg2 $HOME/bin/gpg
            $HOME/bin/gpg --version
            echo RELOADAGENT | gpg-connect-agent
            echo $PGP_SECRET | base64 -di | gpg2 --import --no-tty --batch --yes
            PATH=$HOME/bin:$PATH ./sbt ++${SCALA_VERSION}! clean ci-release

jobs:
  lint:
    <<: *lint
    <<: *machine_ubuntu
    environment:
      - <<: *scala_212
      - <<: *jdk_8

  test_212_jdk8_jvm:
    <<: *testJVM
    <<: *machine_ubuntu
    <<: *machine_resource
    environment:
      - <<: *scala_212
      - <<: *jdk_8

  test_213_jdk8_jvm:
    <<: *testJVM
    <<: *machine_ubuntu
    <<: *machine_resource
    environment:
      - <<: *scala_213
      - <<: *jdk_8

  test_212_jdk11_jvm:
    <<: *testJVM
    <<: *machine_ubuntu
    <<: *machine_resource
    environment:
      - <<: *scala_212
      - <<: *jdk_11

  test_212_jdk8_js:
    <<: *testJS
    <<: *machine_ubuntu
    environment:
      - <<: *scala_212
      - <<: *jdk_8

  test_213_jdk8_js:
    <<: *testJS
    <<: *machine_ubuntu
    environment:
      - <<: *scala_213
      - <<: *jdk_8

  release:
    <<: *release
    <<: *machine_ubuntu
    environment:
      - <<: *scala_213
      - <<: *jdk_8

workflows:
  version: 2
  build:
    jobs:
      - lint:
          filters:
            <<: *filter_tags
      - test_212_jdk8_jvm:
          requires:
            - lint
          filters:
            <<: *filter_tags
      - test_213_jdk8_jvm:
          requires:
            - lint
          filters:
            <<: *filter_tags
      - test_212_jdk11_jvm:
          requires:
            - lint
          filters:
            <<: *filter_tags
      - test_212_jdk8_js:
          requires:
            - lint
          filters:
            <<: *filter_tags
      - test_213_jdk8_js:
          requires:
            - lint
          filters:
            <<: *filter_tags
      - release:
          context: Sonatype2
          requires:
            - test_212_jdk8_jvm
            - test_212_jdk11_jvm
            - test_212_jdk8_js
            - test_213_jdk8_jvm
            - test_213_jdk8_js
          filters:
            <<: *filter_tags
            branches:
              only:
                - master

