lazy val zioSbtVersion = "0.4.1"
addSbtPlugin("dev.zio" % "zio-sbt-website"   % zioSbtVersion)
addSbtPlugin("dev.zio" % "zio-sbt-ci"        % zioSbtVersion)
addSbtPlugin("dev.zio" % "zio-sbt-ecosystem" % zioSbtVersion)

addSbtPlugin("org.scala-js"                      % "sbt-scalajs"               % "1.17.0")
addSbtPlugin("org.portable-scala"                % "sbt-scalajs-crossproject"  % "1.3.2")
addSbtPlugin("org.scalameta"                     % "sbt-scalafmt"              % "2.5.0")
addSbtPlugin("com.eed3si9n"                      % "sbt-buildinfo"             % "0.13.1")
addSbtPlugin("org.scoverage"                     % "sbt-scoverage"             % "2.2.2")
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings"          % "3.0.2")
addSbtPlugin("com.github.cb372"                  % "sbt-explicit-dependencies" % "0.3.1")
addSbtPlugin("ch.epfl.scala"                     % "sbt-bloop"                 % "2.0.17")
addSbtPlugin("com.github.sbt"                    % "sbt-ci-release"            % "1.9.3")
addSbtPlugin("com.timushev.sbt"                  % "sbt-updates"               % "0.6.4")
